# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1936b51e7402204439653322c086165edd3df37246673560ced30f4a6aabc5476b98a603623506b25610db8223ccbac8869508ae26050d0f54dba7aef047075

test:
  secret_key_base: cfad02a782ec497c9eaaf009590435ab781cbb3233523341e563bd6529c3ae1a69fd03f6b06517d72901b0cd9dfe42a0f014be7f9c8782a85990e9c595003c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
